services:
  postgres:
    container_name: 'mental-health-postgres'
    image: 'postgres:15.6'
    environment:
      - POSTGRES_DB=${DB_BASE_NAME}-${PROFILE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db-data-${PROFILE}:/var/lib/postgresql/data
    networks:
      - api
    ports:
      - '${DB_PORT_EXTERNAL}:${DB_PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  api:
    container_name: "mental-health-api"
    build:
      context: .
      dockerfile: Dockerfile
    image: 'mental-health-api'
    ports:
      - 7070:7070
    environment:
      - DB_BASE_NAME=${DB_BASE_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PROFILE=${PROFILE}
    networks:
      - api
    depends_on:
      - postgres

networks:
  api:
    driver: bridge