services:
  postgres:
    container_name: 'mental-health-postgres'
    image: 'postgres:15.6'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_BASE_NAME}-${PROFILE}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./data/postgres/${PROFILE}:/var/lib/postgresql/data
    networks:
      - mental-health-net
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}" ]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: 'mental-health-redis'
    image: 'redis:latest'
    env_file:
      - .env
    ports:
      - ${SPRING_DATA_REDIS_PORT_EXTERNAL}:${SPRING_DATA_REDIS_PORT}
    networks:
      - mental-health-net
    volumes:
      - ./data/redis/${PROFILE}:/data/redis/
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${SPRING_DATA_REDIS_PASSWORD}", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  api:
    container_name: "mental-health-api"
    build:
      context: .
      dockerfile: Dockerfile
    image: 'mental-health-api'
    env_file:
      - .env
    volumes:
      - ./data/api/${PROFILE}:/data/api/
    ports:
      - ${EXTERNAL_API_PORT}:${SERVER_PORT}
    networks:
      - mental-health-net
    depends_on:
      - postgres
      - redis

networks:
  mental-health-net:
    driver: bridge