server:
  port: 80
  servlet:
    context-path: /api


spring:
  application:
    name: mental-health
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_BASE_NAME:mental-health}-${PROFILE:local}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/${DB_BASE_NAME:mental-health}-${PROFILE:local}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      pool-name: HikariPool
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
      jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/${DB_BASE_NAME:mental-health}-${PROFILE:local}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
#    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_BASE_NAME:mental-health}-${PROFILE:local}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/${DB_BASE_NAME:mental-health}-${PROFILE:local}
    driver-class-name: org.postgresql.Driver
    # Fast generate a differential changelog
    # https://www.baeldung.com/liquibase-refactor-schema-of-java-app#generate-the-changelog-in-intellij-idea-using-the-jpa-buddy-plugin
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email


jwt-variables:
  EXPIRES_ACCESS_TOKEN_MINUTE: 120
  EXPIRES_REFRESH_TOKEN_MINUTE: 1
  ISSUER: dev
  KEY: ${JWT_KEY}


logging:
  level:
    org.hibernate: error
    org.springframework: error